name: "generate-snake-game-from-github-contribution-grid"
description: "Generates a snake game from a github user contributions grid. Output the animation as gif or svg"
author: "platane"

runs:
  using: docker
  image: docker://platane/snk@sha256:b107f810d467a26b1e7ac46751073d1247728421155a47e77f6cd2dc66dcc74c

inputs:
  github_user_name:
    description: "github user name"
    required: true
  github_token:
    description: "github token used to fetch the contribution calendar. Default to the action token if empty."
    required: false
    default: ${{ secrets.SNAKE }}
