# Gera a animação do SNK automaticamente usando o GitHub Actions
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gera a animação do Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jonatasu
          github_token: ${{ secrets.SNAKE }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publica SVG na branch output
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
